changelog:
  exclude:
    labels:
      - no-release-note
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Enhancements
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Dependency updates
      labels:
        - bot
        - dependencies
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
